import { promises as fs } from "fs";
import os from "os";
import path from "path";
import { randomUUID } from "crypto";
import { z } from "zod";
import { prisma, type Asset } from "@/lib/db";
import { callChatModel, generateVideo, OpenRouterError } from "@/lib/ai/openrouter";
import { storage, buildStorageKey } from "@/lib/storage";
import { extractLastFrame } from "@/lib/ffmpeg";
import { getSceneVoiceDurationSeconds } from "@/lib/scene-audio";
import { planVideoSegments, splitFixedDurations } from "@/lib/video-segmentation";
import type { VideoModelConfig } from "@/lib/video-model-config";

export interface SerializedSceneVideoClip {
  id: string;
  url: string;
  isSelected: boolean;
  createdAt: Date;
  // Clips generated by one "Generate Video" call share a batchId and are
  // ordered by segmentOrder — see the multi-segment comment on
  // generateSceneVideo below. Both null on legacy single-clip rows.
  batchId: string | null;
  segmentOrder: number | null;
  // Which consecutive shot pair this clip belongs to (0-based). Null for
  // TEXT_TO_VIDEO clips and legacy rows predating per-pair generation.
  pairIndex: number | null;
}

export function serializeSceneVideoClip(asset: Asset): SerializedSceneVideoClip {
  return {
    id: asset.id,
    url: storage.url(asset.storageKey),
    isSelected: asset.isSelected,
    createdAt: asset.createdAt,
    batchId: asset.videoBatchId,
    segmentOrder: asset.videoSegmentOrder,
    pairIndex: asset.videoPairIndex,
  };
}

function extFromMime(mimeType: string): string {
  if (mimeType === "video/webm") return "webm";
  return "mp4";
}

interface GenerateSceneVideoParams {
  sceneId: string;
  modelId: string;
  // The chosen model's admin-configured capabilities (AiModelOption.config),
  // resolved by the caller so this function doesn't need its own lookup.
  // null means "unconfigured" — falls back to one unconstrained-duration
  // segment, matching the pre-multi-segment behavior.
  modelConfig: VideoModelConfig | null;
  resolution?: string;
  generateAudio?: boolean;
}

// IMAGE_TO_VIDEO scenes generate one clip per consecutive shot pair
// (shot[i]->shot[i+1]), so every shot's image is an actual keyframe instead
// of just the first and last mattering. A 1-shot scene is a single
// degenerate "pair" with no end keyframe (plain image animation, as before).
// TEXT_TO_VIDEO scenes don't use shots at all and keep their own flat,
// duration-segmented loop. Either way, segments within one leg (a pair, or
// the whole TEXT_TO_VIDEO clip) beyond what the model can produce in one
// call are frame-chained: each one after the first is seeded with the
// previous call's own last frame (extracted via ffmpeg). All clips from one
// "Generate Video" click share a videoBatchId and a single ascending
// videoSegmentOrder across every pair, so assembly (which just concatenates
// a scene's selected clips in videoSegmentOrder) needs no awareness of
// pairs at all. Generation is necessarily sequential, not parallel, since
// each call can depend on the previous one's output.
export async function generateSceneVideo({
  sceneId,
  modelId,
  modelConfig,
  resolution,
  generateAudio,
}: GenerateSceneVideoParams): Promise<SerializedSceneVideoClip[]> {
  const scene = await prisma.scene.findUniqueOrThrow({
    where: { id: sceneId },
    include: {
      shots: { orderBy: { order: "asc" }, include: { images: { where: { isSelected: true }, take: 1 } } },
    },
  });

  if (scene.visualMode !== "IMAGE_TO_VIDEO" && scene.visualMode !== "TEXT_TO_VIDEO") {
    throw new OpenRouterError("This scene's Visual Mode isn't Image → Video or Text → Video.");
  }

  const resolvedResolution = resolution ?? scene.videoResolution ?? modelConfig?.resolutions?.[0] ?? undefined;
  const resolvedGenerateAudio = generateAudio ?? scene.videoGenerateAudio;

  type SceneShot = (typeof scene.shots)[number];

  async function loadShotImageDataUri(shot: SceneShot): Promise<string> {
    const image = shot.images[0];
    if (!image) {
      throw new OpenRouterError(`Shot ${shot.order} needs a selected image before generating a video clip.`);
    }
    const bytes = await storage.get(image.storageKey);
    if (!bytes) {
      throw new OpenRouterError(`Shot ${shot.order}'s selected image is missing from storage.`);
    }
    return `data:${image.mimeType ?? "image/png"};base64,${bytes.toString("base64")}`;
  }

  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "narrata-video-segment-"));
  try {
    // Deselect the scene's previous take up front, not after — the calls
    // below are sequential external requests that can take minutes and can
    // fail partway through, and leaving the old batch selected while a new
    // one is in progress is a safer failure mode than briefly having two
    // different "selected" batches at once.
    await prisma.asset.updateMany({ where: { videoSceneId: sceneId, isSelected: true }, data: { isSelected: false } });

    const batchId = randomUUID();
    const created: Asset[] = [];
    let globalOrder = 0;

    async function storeClip(
      buffer: Buffer,
      mimeType: string,
      fields: { prompt: string; sourceImageId?: string; videoPairIndex?: number }
    ): Promise<Buffer> {
      const ext = extFromMime(mimeType);
      const order = globalOrder++;
      const fileName = `scene-video-segment${order}.${ext}`;
      const key = buildStorageKey("scenes", sceneId, `${batchId}-${fileName}`);
      await storage.put(key, buffer);
      const asset = await prisma.asset.create({
        data: {
          type: "VIDEO_CLIP",
          storageKey: key,
          fileName,
          mimeType,
          sizeBytes: buffer.byteLength,
          videoSceneId: sceneId,
          isSelected: true,
          modelId,
          createdBy: "AI",
          videoBatchId: batchId,
          videoSegmentOrder: order,
          ...fields,
        },
      });
      created.push(asset);
      return buffer;
    }

    async function chainNextFrame(buffer: Buffer, mimeType: string, label: string): Promise<string> {
      const ext = extFromMime(mimeType);
      const rawPath = path.join(workDir, `${label}.${ext}`);
      await fs.writeFile(rawPath, buffer);
      const framePath = path.join(workDir, `${label}-lastframe.png`);
      await extractLastFrame(rawPath, framePath);
      const frameBytes = await fs.readFile(framePath);
      return `data:image/png;base64,${frameBytes.toString("base64")}`;
    }

    if (scene.visualMode === "IMAGE_TO_VIDEO") {
      if (scene.shots.length === 0) {
        throw new OpenRouterError("Add at least one shot with a selected image before generating a video clip.");
      }
      scene.shots.forEach((shot, i) => {
        if (!shot.images[0]) {
          throw new OpenRouterError(`Shot ${i + 1} needs a selected image before generating a video clip.`);
        }
      });

      // Target duration: an explicit manual override wins; otherwise fall
      // back to the scene's actual narration+dialogue length (ffprobe'd real
      // audio, not an estimate). Split evenly across pairs unless a pair's
      // own starting shot has an explicit durationSeconds override.
      const sceneTargetDuration = scene.videoDurationSeconds ?? (await getSceneVoiceDurationSeconds(sceneId));

      const pairs: { startShot: SceneShot; endShot: SceneShot | undefined }[] =
        scene.shots.length === 1
          ? [{ startShot: scene.shots[0], endShot: undefined }]
          : scene.shots.slice(0, -1).map((startShot, i) => ({ startShot, endShot: scene.shots[i + 1] }));

      // Auto-split baseline for pairs with no explicit Shot.durationSeconds
      // override: for a fixed-duration model, distribute the scene's whole
      // target across every pair at once (see splitFixedDurations) so the
      // total lands close to the target — e.g. 14s over 2 pairs on [4,6,8]s
      // options becomes [8,6], not two independently-rounded 8s legs
      // overshooting to 16s. Anything else (range-mode/unconfigured) falls
      // back to a plain even split; each leg's own planVideoSegments call
      // below still clamps it sensibly on its own in that case.
      const autoPairTargets =
        sceneTargetDuration && modelConfig?.durationMode === "fixed"
          ? splitFixedDurations(sceneTargetDuration, pairs.length, modelConfig.fixedDurations ?? [])
          : pairs.map(() => (sceneTargetDuration ? sceneTargetDuration / pairs.length : undefined));

      for (const [pairIndex, pair] of pairs.entries()) {
        const startDataUri = await loadShotImageDataUri(pair.startShot);
        const endDataUri = pair.endShot ? await loadShotImageDataUri(pair.endShot) : undefined;
        const pairPrompt =
          scene.motionPrompt?.trim() ||
          (pair.endShot
            ? `${scene.description}\n\nTransition: from "${pair.startShot.description}" to "${pair.endShot.description}"`
            : scene.description);

        const pairTarget = pair.startShot.durationSeconds ?? autoPairTargets[pairIndex];
        const subSegmentDurations = pairTarget ? planVideoSegments(pairTarget, modelConfig).durations : [undefined];

        let chainedFrame = startDataUri;
        for (const [subIndex, subDuration] of subSegmentDurations.entries()) {
          const isLastSub = subIndex === subSegmentDurations.length - 1;
          const generated = await generateVideo({
            modelId,
            prompt: pairPrompt,
            imageDataUri: chainedFrame,
            lastFrameDataUri: isLastSub ? endDataUri : undefined,
            durationSeconds: subDuration,
            generateAudio: resolvedGenerateAudio,
            resolution: resolvedResolution,
          });

          const buffer = Buffer.from(generated.base64, "base64");
          await storeClip(buffer, generated.mimeType, {
            prompt: pairPrompt,
            sourceImageId: subIndex === 0 ? pair.startShot.images[0]?.id : undefined,
            videoPairIndex: pairIndex,
          });

          if (!isLastSub) {
            chainedFrame = await chainNextFrame(buffer, generated.mimeType, `pair${pairIndex}-seg${subIndex}`);
          }
        }
      }
    } else {
      const prompt = scene.videoPrompt?.trim() || scene.description;
      const targetDuration = scene.videoDurationSeconds ?? (await getSceneVoiceDurationSeconds(sceneId));
      const segmentDurations = targetDuration ? planVideoSegments(targetDuration, modelConfig).durations : [undefined];

      let chainedFrame: string | undefined;
      for (const [index, segmentDuration] of segmentDurations.entries()) {
        const generated = await generateVideo({
          modelId,
          prompt,
          imageDataUri: chainedFrame,
          durationSeconds: segmentDuration,
          generateAudio: resolvedGenerateAudio,
          resolution: resolvedResolution,
        });

        const buffer = Buffer.from(generated.base64, "base64");
        await storeClip(buffer, generated.mimeType, { prompt });

        if (index < segmentDurations.length - 1) {
          chainedFrame = await chainNextFrame(buffer, generated.mimeType, `segment${index}`);
        }
      }
    }

    return created.map(serializeSceneVideoClip);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true });
  }
}

const MOTION_PROMPT_SYSTEM_PROMPT = `You are the Motion Prompt drafting step inside Narrata, a manual-first AI story/video production studio.
Write a short camera/motion direction prompt for an image-to-video model, continuing smoothly from the previous scene and animating the attached current-scene image.
Describe only camera movement, subject motion, and action beats — not dialogue or narration, those are separate tracks handled elsewhere.
Respond with the motion prompt text only — no labels, quotation marks, or commentary.`;

interface DraftMotionPromptParams {
  sceneId: string;
  modelId: string;
}

// Reads the previous scene's generated clip (visually and, via OpenRouter's
// video-input content part, its audio too) plus the current scene's selected
// starting frame, in one multimodal call — grounding the drafted motion
// prompt in what actually happened last, not just what was planned. Falls
// back to the previous scene's description text when it has no selected clip
// yet (first scene, or video not generated yet). Returns a draft only — the
// caller/UI decides whether to accept it into the editable motionPrompt
// field, same "AI drafts, user approves" pattern as every other drafting job.
export async function draftMotionPrompt({ sceneId, modelId }: DraftMotionPromptParams): Promise<string> {
  const scene = await prisma.scene.findUniqueOrThrow({
    where: { id: sceneId },
    include: {
      shots: { orderBy: { order: "asc" }, take: 1, include: { images: { where: { isSelected: true }, take: 1 } } },
    },
  });

  if (scene.visualMode !== "IMAGE_TO_VIDEO") {
    throw new OpenRouterError("Motion prompt drafting only applies to Image → Video scenes.");
  }

  const currentImage = scene.shots[0]?.images[0];
  if (!currentImage) {
    throw new OpenRouterError("Generate and select a first-shot image before drafting a motion prompt.");
  }
  const currentImageBytes = await storage.get(currentImage.storageKey);
  if (!currentImageBytes) {
    throw new OpenRouterError("The first shot's selected image is missing from storage.");
  }
  const currentImageDataUri = `data:${currentImage.mimeType ?? "image/png"};base64,${currentImageBytes.toString("base64")}`;

  const parentWhere = scene.storyId ? { storyId: scene.storyId } : { episodeId: scene.episodeId! };
  const previousScene = await prisma.scene.findFirst({
    where: { ...parentWhere, order: scene.order - 1 },
    // The *last* segment of the previous scene's selected batch — that's
    // the frame this scene actually continues from when the previous scene
    // was multi-segment, not its first.
    include: { videoClips: { where: { isSelected: true }, orderBy: { videoSegmentOrder: "desc" }, take: 1 } },
  });

  let previousVideoDataUri: string | undefined;
  const previousClip = previousScene?.videoClips[0];
  if (previousClip) {
    const clipBytes = await storage.get(previousClip.storageKey);
    if (clipBytes) {
      previousVideoDataUri = `data:${previousClip.mimeType ?? "video/mp4"};base64,${clipBytes.toString("base64")}`;
    }
  }

  const previousContext = !previousScene
    ? "This is the first scene — there is no preceding scene."
    : previousVideoDataUri
      ? "The attached video is the immediately preceding scene's generated clip — watch and listen to it (dialogue, sound, motion, camera, ending framing) before writing the motion prompt below, so this scene continues naturally from it."
      : `The immediately preceding scene has no generated clip yet. Its description: "${previousScene.description}"`;

  const userPrompt = `# Previous scene\n${previousContext}\n\n# Current scene\nDescription: ${scene.description}\nThe attached image is this scene's starting frame — motion should build on what's actually in it, not a generic description.\n\nWrite the motion prompt now.`;

  const draft = await callChatModel({
    modelId,
    systemPrompt: MOTION_PROMPT_SYSTEM_PROMPT,
    userPrompt,
    images: [currentImageDataUri],
    videos: previousVideoDataUri ? [previousVideoDataUri] : undefined,
    temperature: 0.7,
  });

  return draft.trim();
}

const DURATION_RECOMMENDATION_SYSTEM_PROMPT = `You are the Duration Recommendation step inside Narrata, a manual-first AI story/video production studio.
Read the scene below and recommend how many seconds its generated video clip should run.

Judge pacing like an editor: a quick action beat or a single line of dialogue runs shorter; a slow establishing shot, a wide emotional beat, or a scene carrying more spoken content runs longer. If a "Spoken audio" length is given, treat it as a floor the clip must cover, not a ceiling — pad for visual breathing room (a beat before/after the line) rather than cutting it flush.

Respond with strict JSON only — no prose, no markdown code fences, no commentary. The JSON must match this shape exactly:
{
  "durationSeconds": a whole number of seconds, typically between 2 and 30,
  "reason": "one short sentence explaining the pacing call"
}`;

const durationRecommendationSchema = z.object({
  durationSeconds: z.number().positive(),
  reason: z.string().min(1),
});

export interface DurationRecommendation {
  durationSeconds: number;
  reason: string;
}

interface RecommendVideoDurationParams {
  sceneId: string;
  modelId: string;
}

// Text-only reasoning call (no image/video input, unlike draftMotionPrompt
// above) — feeds the recommended seconds into the same editable `duration`
// field the panel already has, same "AI proposes, user reviews and saves"
// idiom as the rest of this file. voiceDurationSeconds (from
// getSceneVoiceDurationSeconds, already used as the *generation-time*
// fallback when duration is left blank) is passed here too, as a floor hint
// rather than the answer itself — a scene can run longer than its dialogue
// for visual pacing, just never shorter.
export async function recommendVideoDuration({ sceneId, modelId }: RecommendVideoDurationParams): Promise<DurationRecommendation> {
  const scene = await prisma.scene.findUniqueOrThrow({ where: { id: sceneId } });

  const voiceDurationSeconds = await getSceneVoiceDurationSeconds(sceneId);
  const motionOrVideoPrompt =
    scene.visualMode === "TEXT_TO_VIDEO" ? scene.videoPrompt : scene.motionPrompt;

  const promptLines = [
    `Description: ${scene.description}`,
    motionOrVideoPrompt?.trim() ? `Motion/video prompt: ${motionOrVideoPrompt.trim()}` : null,
    scene.narration?.trim() ? `Narration: ${scene.narration.trim()}` : null,
    voiceDurationSeconds ? `Spoken audio: ${Math.round(voiceDurationSeconds * 10) / 10}s of recorded narration/dialogue already exists for this scene.` : null,
  ].filter((line): line is string => line !== null);

  const raw = await callChatModel({
    modelId,
    systemPrompt: DURATION_RECOMMENDATION_SYSTEM_PROMPT,
    userPrompt: `# Scene\n${promptLines.join("\n")}\n\nRecommend the duration now.`,
    jsonMode: true,
    temperature: 0.4,
  });

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(raw);
  } catch {
    throw new OpenRouterError("AI returned invalid JSON.");
  }

  const parsed = durationRecommendationSchema.safeParse(parsedJson);
  if (!parsed.success) {
    throw new OpenRouterError("AI returned an unexpected shape.");
  }

  // The floor above is a prompt instruction, not a guarantee — models do
  // ignore it (seen in practice: 14s suggested against 33s of already-
  // recorded narration). Enforce it in code too, same as the
  // generation-time fallback already treats voice length as authoritative
  // (see getSceneVoiceDurationSeconds's callers). Rounds the floor up so the
  // clip fully covers the audio rather than landing a fraction short of it.
  const floor = voiceDurationSeconds ? Math.ceil(voiceDurationSeconds) : 0;
  const durationSeconds = Math.max(Math.round(parsed.data.durationSeconds), floor);
  const reason =
    durationSeconds > Math.round(parsed.data.durationSeconds)
      ? `${parsed.data.reason} (raised from the AI's ${Math.round(parsed.data.durationSeconds)}s to cover the ${floor}s of existing narration/dialogue audio.)`
      : parsed.data.reason;

  return { durationSeconds, reason };
}

export async function getSceneVideoClips(sceneId: string): Promise<SerializedSceneVideoClip[]> {
  const assets = await prisma.asset.findMany({
    where: { videoSceneId: sceneId },
    orderBy: [{ createdAt: "desc" }, { videoSegmentOrder: "asc" }],
  });
  return assets.map(serializeSceneVideoClip);
}

// Selecting a clip selects its whole batch (every segment generated by the
// same call) — a batch is one "take"; partial selection can't be assembled
// into a coherent clip. Legacy rows with no batchId (single-clip, pre
// multi-segment) fall back to selecting just that one asset.
export async function selectSceneVideoClip(sceneId: string, assetId: string): Promise<SerializedSceneVideoClip[]> {
  return prisma.$transaction(async (tx) => {
    const asset = await tx.asset.findUniqueOrThrow({ where: { id: assetId } });
    if (asset.videoSceneId !== sceneId) {
      throw new Error("Video clip does not belong to this scene.");
    }
    await tx.asset.updateMany({ where: { videoSceneId: sceneId, isSelected: true }, data: { isSelected: false } });
    const where = asset.videoBatchId ? { videoSceneId: sceneId, videoBatchId: asset.videoBatchId } : { id: assetId };
    await tx.asset.updateMany({ where, data: { isSelected: true } });
    const batch = await tx.asset.findMany({ where, orderBy: { videoSegmentOrder: "asc" } });
    return batch.map(serializeSceneVideoClip);
  });
}

// Deletes the whole batch a clip belongs to — a partial take (missing one of
// its segments) can't be assembled, so there's no useful state to leave
// behind by deleting just one segment. Legacy rows with no batchId delete
// just that one asset, same as before.
export async function deleteSceneVideoClip(sceneId: string, assetId: string): Promise<void> {
  const asset = await prisma.asset.findUniqueOrThrow({ where: { id: assetId } });
  if (asset.videoSceneId !== sceneId) {
    throw new Error("Video clip does not belong to this scene.");
  }
  const batch = asset.videoBatchId
    ? await prisma.asset.findMany({ where: { videoSceneId: sceneId, videoBatchId: asset.videoBatchId } })
    : [asset];
  for (const clip of batch) {
    await storage.remove(clip.storageKey);
  }
  await prisma.asset.deleteMany({ where: { id: { in: batch.map((c) => c.id) } } });
}

// Mirrors mapSceneVoiceData in lib/voice.ts — for the scene pages' initial
// SSR load, serializing the videoClips relation the same way the API routes
// below do, so the client gets an identical shape regardless of source.
export function mapSceneVideoData<T extends { videoClips: Asset[] }>(scene: T) {
  return {
    ...scene,
    videoClips: scene.videoClips.map(serializeSceneVideoClip),
  };
}
