import { promises as fs } from "fs";
import os from "os";
import path from "path";
import { randomUUID } from "crypto";
import { z } from "zod";
import { prisma, type Asset, type CameraMovement } from "@/lib/db";
import { callChatModel, generateVideo, OpenRouterError } from "@/lib/ai/openrouter";
import { storage, buildStorageKey } from "@/lib/storage";
import { extractLastFrame, detectFrozenSeconds, probeDuration } from "@/lib/ffmpeg";
import { getSceneVoiceDurationSeconds } from "@/lib/scene-audio";
import { planVideoSegments, splitFixedDurations } from "@/lib/video-segmentation";
import { loadReferenceDataUris, validationResponseSchema, type ValidationEntity } from "@/lib/shot-images";
import { parseContinuitySnapshot } from "@/lib/scene-continuity";
import {
  SHOT_SIZE_LABELS,
  CAMERA_ANGLE_LABELS,
  DEPTH_OF_FIELD_LABELS,
  LIGHTING_STYLE_LABELS,
  hasCameraDirection,
  type ShotCinematography,
} from "@/lib/cinematography";
import { parseVideoModelConfig, type VideoModelConfig } from "@/lib/video-model-config";
import { listModelsForJob } from "@/lib/ai/models";
import { STALE_MS } from "@/lib/generation-claims";
import { recordGenerationEvent, resolveSceneProjectId } from "@/lib/generation-events";
import type { PromptBuilderFields } from "@/components/video-prompt-builder";

// Same claim/release contract as claimShotForImageGeneration in
// shot-images.ts — atomic updateMany so two concurrent requests can't both
// win the claim.
export async function claimSceneVideoGeneration(sceneId: string): Promise<boolean> {
  const staleThreshold = new Date(Date.now() - STALE_MS.video);
  const result = await prisma.scene.updateMany({
    where: {
      id: sceneId,
      OR: [{ videoGenerationStartedAt: null }, { videoGenerationStartedAt: { lt: staleThreshold } }],
    },
    data: { videoGenerationStartedAt: new Date() },
  });
  return result.count > 0;
}

export async function releaseSceneVideoGeneration(sceneId: string): Promise<void> {
  await prisma.scene.update({ where: { id: sceneId }, data: { videoGenerationStartedAt: null } });
}

export interface SerializedSceneVideoClip {
  id: string;
  url: string;
  isSelected: boolean;
  createdAt: Date;
  // Clips generated by one "Generate Video" call share a batchId and are
  // ordered by segmentOrder — see the multi-segment comment on
  // generateSceneVideo below. Both null on legacy single-clip rows.
  batchId: string | null;
  segmentOrder: number | null;
  // Which consecutive shot pair this clip belongs to (0-based). Null for
  // TEXT_TO_VIDEO clips and legacy rows predating per-pair generation.
  pairIndex: number | null;
  // Advisory-only auto-QC signal (see checkSegmentFrozen in this file) —
  // null means not checked (e.g. a STATIC-camera shot), never a failure.
  qcPassed: boolean | null;
  qcNotes: string | null;
  // Advisory-only tier-2 critic signal (see runVideoValidation) — identity/
  // reference/continuity/prompt-adherence, distinct from qcPassed's freeze
  // detection. null means not checked (no VIDEO_VALIDATION model
  // configured), never a failure.
  validationPassed: boolean | null;
  validationNotes: string | null;
  // Which model actually generated this segment (a pair's own resolved
  // model, not necessarily the scene's default — see resolvePairModel in
  // buildImageToVideoPlan) and the exact prompt sent to it. Surfaced in the
  // Takes panel's per-clip details so an off-looking 45s scene can be
  // diagnosed pair-by-pair instead of guessed at.
  modelId: string | null;
  prompt: string | null;
  // Whether this segment's generateVideo call actually included the pair's
  // end-frame keyframe. null for TEXT_TO_VIDEO/legacy rows.
  usedEndFrame: boolean | null;
}

export function serializeSceneVideoClip(asset: Asset): SerializedSceneVideoClip {
  return {
    id: asset.id,
    url: storage.url(asset.storageKey),
    isSelected: asset.isSelected,
    createdAt: asset.createdAt,
    batchId: asset.videoBatchId,
    segmentOrder: asset.videoSegmentOrder,
    pairIndex: asset.videoPairIndex,
    qcPassed: asset.qcPassed,
    qcNotes: asset.qcNotes,
    validationPassed: asset.validationPassed,
    validationNotes: asset.validationNotes,
    modelId: asset.modelId,
    prompt: asset.prompt,
    usedEndFrame: asset.usedEndFrame,
  };
}

function extFromMime(mimeType: string): string {
  if (mimeType === "video/webm") return "webm";
  return "mp4";
}

// Shot.cameraMovement (set by generateShots' shot breakdown, see shots.ts) is
// otherwise never read again — this is what actually surfaces it to the
// video model, since free-text prompts alone get inconsistent camera-motion
// adherence across providers.
// Unlike the ILLUSTRATION path (buildCameraFilter, video-assembly.ts) — where
// a still image forces dolly and zoom to collapse into the same affine
// transform — a video model can actually render the difference between an
// optical zoom and a camera that physically travels. So each value gets prose
// that names the distinction explicitly rather than a generic "moves closer":
// a model told to "zoom" will hold perspective flat, and one told to "dolly"
// will move the background against the subject.
function cameraMovementInstruction(movement: CameraMovement): string {
  switch (movement) {
    case "ZOOM_IN":
      return "Camera: slow optical zoom in — the camera itself stays put and the lens tightens; perspective and parallax stay unchanged.";
    case "ZOOM_OUT":
      return "Camera: slow optical zoom out — the camera itself stays put and the lens widens; perspective and parallax stay unchanged.";
    case "DOLLY_IN":
      return "Camera: slow dolly in — the camera physically pushes toward the subject, background sliding past with real parallax. This is a move through space, not a zoom.";
    case "DOLLY_OUT":
      return "Camera: slow dolly out — the camera physically pulls back from the subject, revealing more of the space with real parallax. This is a move through space, not a zoom.";
    case "PAN_LEFT":
      return "Camera: pans left — the camera pivots in place, its position fixed.";
    case "PAN_RIGHT":
      return "Camera: pans right — the camera pivots in place, its position fixed.";
    case "CRASH_ZOOM":
      return "Camera: crash zoom — a fast, aggressive optical zoom snapped in over a beat rather than eased. The camera does not move; only the lens.";
    case "DOLLY_ZOOM":
      return "Camera: dolly zoom (the Vertigo effect) — track the camera toward the subject while zooming the lens the opposite way, so the subject stays exactly the same size in frame while the background stretches and warps behind them. The disorienting background shift is the whole point.";
    case "TILT_UP":
      return "Camera: tilts up — the camera pivots upward in place, its position fixed; it does not rise.";
    case "TILT_DOWN":
      return "Camera: tilts down — the camera pivots downward in place, its position fixed; it does not descend.";
    case "WHIP_PAN":
      return "Camera: whip pan — a very fast horizontal pan that smears the frame into motion blur before settling.";
    case "ROLL":
      return "Camera: rolls — the camera rotates around its own lens axis so the horizon tilts. The camera does not move through space and does not pivot up or down.";
    case "PEDESTAL_UP":
      return "Camera: pedestals up — the camera body rises straight up while holding its angle, so the framing translates upward. It is not tilting; the lens keeps pointing the same way.";
    case "PEDESTAL_DOWN":
      return "Camera: pedestals down — the camera body drops straight down while holding its angle, so the framing translates downward. It is not tilting; the lens keeps pointing the same way.";
    case "ARC_LEFT":
      return "Camera: arcs left — the camera orbits around the subject to the left, keeping them centred while the background rotates behind them.";
    case "ARC_RIGHT":
      return "Camera: arcs right — the camera orbits around the subject to the right, keeping them centred while the background rotates behind them.";
    case "STEADICAM_FOLLOW":
      return "Camera: steadicam follow — a smooth, stabilized, gliding move that stays with the subject through the space. Fluid and floating, with none of handheld's shake.";
    case "AERIAL":
      return "Camera: aerial — an airborne drone vantage high above the scene, drifting slowly to show the geography and scale below.";
    case "TRACK_LEFT":
      return "Camera: tracks left — the whole camera travels laterally leftward alongside the scene, holding its angle rather than pivoting.";
    case "TRACK_RIGHT":
      return "Camera: tracks right — the whole camera travels laterally rightward alongside the scene, holding its angle rather than pivoting.";
    case "CRANE_UP":
      return "Camera: cranes up — the camera rises vertically through the space, the viewpoint genuinely lifting rather than merely tilting.";
    case "CRANE_DOWN":
      return "Camera: cranes down — the camera descends vertically through the space, the viewpoint genuinely dropping rather than merely tilting.";
    case "HANDHELD":
      return "Camera: handheld — subtle, continuous, naturalistic unsteadiness as if hand-carried, with no overall direction of travel. Keep the amplitude small; this is texture, not a move.";
    case "STATIC":
      return "Camera: static, no camera movement.";
    default: {
      // Compile-time exhaustiveness — see buildCameraFilter for the same
      // pattern and reasoning.
      const unhandled: never = movement;
      void unhandled;
      return "Camera: static, no camera movement.";
    }
  }
}

// A pair/scene leg longer than the model's own max duration is frame-chained
// into several calls (see chainNextFrame) — each one after the first is
// seeded with the previous call's own last frame. Sending every sub-segment
// the same unqualified prompt reads, to the model, as "start this action from
// scratch," so a mid-motion frame tends to get the opening action replayed
// instead of continued. Tagging each call with its position fixes that.
function subSegmentPrompt(basePrompt: string, subIndex: number, total: number): string {
  if (total <= 1) return basePrompt;
  const isLast = subIndex === total - 1;
  const positionNote =
    subIndex === 0
      ? `This is segment 1 of ${total} — begin the motion described above.`
      : isLast
        ? `This is segment ${subIndex + 1} of ${total}, continuing directly from the motion already in progress — do not restart or repeat the earlier action. Bring the motion to completion.`
        : `This is segment ${subIndex + 1} of ${total}, continuing directly from the motion already in progress — do not restart or repeat the earlier action.`;
  return `${basePrompt}\n\n${positionNote}`;
}

async function loadSceneForVideoGeneration(sceneId: string) {
  return prisma.scene.findUniqueOrThrow({
    where: { id: sceneId },
    include: {
      shots: { orderBy: { order: "asc" }, include: { images: { where: { isSelected: true }, take: 1 } } },
      characters: { include: { referenceImages: true } },
      locations: { include: { referenceImages: true } },
    },
  });
}

type SceneForVideo = Awaited<ReturnType<typeof loadSceneForVideoGeneration>>;
type SceneShot = SceneForVideo["shots"][number];

async function loadShotImageDataUri(shot: SceneShot): Promise<string> {
  const image = shot.images[0];
  if (!image) {
    throw new OpenRouterError(`Shot ${shot.order} needs a selected image before generating a video clip.`);
  }
  const bytes = await storage.get(image.storageKey);
  if (!bytes) {
    throw new OpenRouterError(`Shot ${shot.order}'s selected image is missing from storage.`);
  }
  return `data:${image.mimeType ?? "image/png"};base64,${bytes.toString("base64")}`;
}

// Same roster generateShotImage() uses for image-generation consistency —
// locked characters (an unlocked character's look is allowed to vary, so
// it isn't a reference worth pinning) plus every tagged location.
async function resolveCastReferenceDataUris(scene: SceneForVideo, includeCastReferences: boolean | undefined): Promise<string[]> {
  const castTargets: ValidationEntity[] = [
    ...scene.characters.filter((c) => c.isLocked).map((c) => ({ name: c.name, referenceImages: c.referenceImages })),
    ...scene.locations.map((l) => ({ name: l.name, referenceImages: l.referenceImages })),
  ].filter((t) => t.referenceImages.length > 0);
  return includeCastReferences && castTargets.length > 0 ? loadReferenceDataUris(castTargets) : [];
}

// Locked characters + all tagged locations with an uploaded reference image —
// same roster generateShotImage() uses for image-generation consistency (see
// shot-images.ts's validationTargets). Unlike resolveCastReferenceDataUris
// above (opt-in generation conditioning via includeCastReferences), this
// always runs whenever a VIDEO_VALIDATION model is configured.
function resolveValidationTargets(scene: SceneForVideo): ValidationEntity[] {
  return [
    ...scene.characters.filter((c) => c.isLocked).map((c) => ({ name: c.name, referenceImages: c.referenceImages })),
    ...scene.locations.map((l) => ({ name: l.name, referenceImages: l.referenceImages })),
  ].filter((t) => t.referenceImages.length > 0);
}

// Tier-2 quality/continuity critic for a generated VIDEO_CLIP segment —
// mirrors shot-images.ts's runValidation one step over (video_url input
// instead of a still), reusing its exact {passed, notes} response contract.
// Face/identity drift is called out as the single most important failure
// mode: a still-image reference check can miss a face that warps or drifts
// mid-clip, which a per-frame-aware video model can actually catch.
const VIDEO_VALIDATION_SYSTEM_PROMPT = `You are the Video Validation step of Narrata's video pipeline. The attached video is a newly generated shot clip. Any attached images are locked reference images for named characters/locations, given in the order listed in the user prompt.

Judge whether the people and places in the clip stay visually consistent with those references for the clip's full duration — pay closest attention to faces: eyes, nose, mouth, jaw and overall face shape must read as the same identity as the reference from the first frame to the last. A face that drifts, warps, loses or gains features, or reads as a different person at any point in the clip is a failure even if the opening frame matched — this is the single most important thing to check, ahead of general style or lighting drift.

When continuity facts are listed in the user prompt, also judge whether the clip honors them — a clip that silently drops or contradicts carried state (a prop that should still be held, a wardrobe or physical change that should show) counts as a failure the same way a mismatched reference does.

When a requested camera/motion direction is listed, judge whether the clip's actual camera movement and action match it — minor timing differences are fine, but the wrong camera move or action counts as a failure.

Respond with strict JSON only — no prose, no markdown code fences. The JSON must match this shape exactly:
{ "passed": true or false, "notes": "one or two sentences explaining the judgment, covering identity/reference consistency, continuity, and prompt adherence whenever each applied" }`;

async function runVideoValidation(
  generatedVideoDataUri: string,
  entities: ValidationEntity[],
  referenceDataUris: string[],
  modelId: string,
  continuitySnapshot: { subject: string; state: string }[],
  continuityNotes: string | null,
  requestedDirection: string | null
): Promise<{ passed: boolean; notes: string }> {
  const continuityFacts = [...continuitySnapshot.map((e) => `${e.subject} — ${e.state}`), continuityNotes].filter(
    (v): v is string => Boolean(v)
  );
  const continuityLine = continuityFacts.length > 0 ? `\n\nContinuity to preserve: ${continuityFacts.join("; ")}` : "";
  const directionLine = requestedDirection ? `\n\nRequested camera/motion direction: ${requestedDirection}` : "";
  const referenceLine =
    entities.length > 0
      ? `Reference images, in order: ${entities.map((e) => e.name).join(", ")}.`
      : "No locked reference images for this clip.";

  const userPrompt = `${referenceLine}${directionLine}${continuityLine}\n\nDoes the generated video clip stay consistent with the references (if any), honor the continuity requirements (if any), and match the requested direction (if any)? Respond with the required JSON.`;

  const raw = await callChatModel({
    modelId,
    systemPrompt: VIDEO_VALIDATION_SYSTEM_PROMPT,
    userPrompt,
    jsonMode: true,
    images: referenceDataUris,
    videos: [generatedVideoDataUri],
  });

  const parsed = validationResponseSchema.safeParse(JSON.parse(raw));
  if (!parsed.success) {
    throw new OpenRouterError("Video validation model returned an unexpected shape.");
  }
  return parsed.data;
}

async function chainNextFrame(workDir: string, buffer: Buffer, mimeType: string, label: string): Promise<string> {
  const ext = extFromMime(mimeType);
  const rawPath = path.join(workDir, `${label}.${ext}`);
  await fs.writeFile(rawPath, buffer);
  const framePath = path.join(workDir, `${label}-lastframe.png`);
  await extractLastFrame(rawPath, framePath);
  const frameBytes = await fs.readFile(framePath);
  return `data:image/png;base64,${frameBytes.toString("base64")}`;
}

// Director AI cinematography (Shot.shotSize/lensMm/…) → clip direction.
//
// Optics and light come from the START shot only, deliberately: a pair is
// one continuous take, and a lens/angle/lighting value that changed halfway
// through would read as a cut rather than a move. The one thing that legitimately
// changes across a pair is shot size — that's precisely what the camera move
// is for, so a start≠end size becomes an explicit "begins as X, ends on Y".
//
// composition/framing/focusPoint are deliberately NOT restated here: unlike
// the image pipeline, this call already receives the start shot's rendered
// image as its first frame, so the composition is literally visible to the
// model and repeating it in words only risks contradicting the picture.
//
// Returns null when the shot has no resolved direction at all (legacy or
// hand-added shots) — same "null means silent" rule as the image prompt.
function shotDirectionInstruction(startShot: SceneShot, endShot: SceneShot | undefined): string | null {
  const optics = [
    startShot.lensMm !== null && `${startShot.lensMm}mm lens`,
    startShot.cameraAngle && CAMERA_ANGLE_LABELS[startShot.cameraAngle],
    startShot.depthOfField && DEPTH_OF_FIELD_LABELS[startShot.depthOfField],
    startShot.lightingStyle && LIGHTING_STYLE_LABELS[startShot.lightingStyle],
  ].filter(Boolean);

  const framingLine =
    endShot && startShot.shotSize && endShot.shotSize && startShot.shotSize !== endShot.shotSize
      ? `Framing: begins as a ${SHOT_SIZE_LABELS[startShot.shotSize]} and ends on a ${SHOT_SIZE_LABELS[endShot.shotSize]} — the camera move is what carries it there.`
      : startShot.shotSize
        ? `Framing: holds a ${SHOT_SIZE_LABELS[startShot.shotSize]} throughout.`
        : null;

  const lines = [
    optics.length > 0 &&
      `Optics and light: ${optics.join(", ")}. These are one continuous take — hold them steady for the whole clip, never change lens, angle or lighting mid-clip.`,
    framingLine,
    startShot.subjectMovement && `Subject movement: ${startShot.subjectMovement}`,
  ].filter(Boolean);

  return lines.length > 0 ? `Shot direction (resolved by the Director for this shot):\n${lines.join("\n")}` : null;
}

// A pair's start image is a real rendered still of that exact shot, so the
// video model can already see the subject's pose there — what a single still
// can't convey is momentum: whether that pose is mid-run or about to begin
// running. Left unstated, a mid-action starting frame tends to get
// re-interpreted as the start of a fresh beat, the same failure subSegmentPrompt
// (above) already exists to prevent one level down, within a single pair's own
// frame-chained sub-segments — this is that fix applied across the pair
// boundary instead.
//
// Camera-aware: when the Director kept the same CameraMovement across the
// cut, the camera's own motion is one continuous move spanning both pairs, so
// it gets told to continue alongside the subject. When the Director changed
// it, the new camera move is a deliberate instruction — telling the model to
// also continue the *previous* shot's camera motion here would fight
// cameraMovementInstruction's line for this pair, so only the subject's
// physical action is carried forward, and the note says explicitly to follow
// the new camera direction rather than the old one. undefined previousPair
// (the scene's first pair) returns null — there is no prior shot to continue
// from.
function crossPairContinuationNote(pair: PairPlan, previousPair: PairPlan | undefined): string | null {
  if (!previousPair) return null;
  const priorMotion = previousPair.startShot.subjectMovement?.trim();
  const motionClause = priorMotion ? `"${priorMotion}" was already in progress` : "motion was already in progress";
  const sameCameraMovement = pair.startShot.cameraMovement === previousPair.startShot.cameraMovement;

  return sameCameraMovement
    ? `Continuing directly from the previous shot: ${motionClause} as this shot begins, and the camera's own movement continues too — this is one continuous motion spanning the cut, not a fresh beginning. Continue both the subject's action and the camera's motion rather than restarting either.`
    : `Continuing directly from the previous shot: ${motionClause} as this shot begins — the starting frame is a mid-action moment, not a fresh beginning. Continue the subject's motion, but the camera direction below is a deliberate change from the previous shot's — follow it fully rather than carrying over the previous shot's camera movement.`;
}

// motionPrompt is pure camera/motion direction "layered on top of" the scene
// (see its schema comment and MOTION_PROMPT_SYSTEM_PROMPT below), so the
// description/transition text is always included and motionPrompt — when
// set — is appended rather than replacing it. cameraMovementInstruction adds
// the pair's starting shot's own camera direction on top of that.
//
// Precedence between the two direction sources is stated in the prompt
// rather than left to ordering: motionPrompt is human-typed (or a human-
// approved draft) scene-level text, so it outranks the per-shot Director
// fields wherever the two disagree. Director AI never writes into
// motionPrompt itself — the only writer is the user, via the Prompt Builder.
function buildPairPrompt(scene: SceneForVideo, pair: PairPlan, previousPair: PairPlan | undefined): string {
  const descriptionOrTransition = pair.endShot
    ? `${scene.description}\n\nTransition: from "${pair.startShot.description}" to "${pair.endShot.description}"`
    : scene.description;
  const shotDirection = shotDirectionInstruction(pair.startShot, pair.endShot);
  const motion = scene.motionPrompt?.trim();

  return [
    descriptionOrTransition,
    crossPairContinuationNote(pair, previousPair),
    shotDirection,
    motion && `Motion (director override): ${motion}`,
    cameraMovementInstruction(pair.startShot.cameraMovement),
    shotDirection &&
      motion &&
      "Where the director override conflicts with the shot direction above, follow the override — it is the human director's instruction for this scene.",
  ]
    .filter(Boolean)
    .join("\n\n");
}

interface PairPlan {
  startShot: SceneShot;
  endShot: SceneShot | undefined;
}

interface ResolvedPairModel {
  modelId: string;
  modelConfig: VideoModelConfig | null;
}

// Builds the consecutive shot-pair breakdown for an IMAGE_TO_VIDEO scene,
// resolves each pair's model (manual Shot.videoModelId override, else a
// CameraMovement-routing rule, else the scene-level fallback — see
// resolvePairModel below), and plans each pair's target duration. Shared by
// generateSceneVideo (the whole scene) and regenerateScenePairVideo (a
// single pair retake) so both use identical planning.
async function buildImageToVideoPlan(
  scene: SceneForVideo,
  sceneId: string,
  fallback: ResolvedPairModel
): Promise<{
  pairs: PairPlan[];
  pairModels: ResolvedPairModel[];
  sceneTargetDuration: number | null;
  autoPairTargets: (number | undefined)[];
}> {
  const sceneTargetDuration = scene.videoDurationSeconds ?? (await getSceneVoiceDurationSeconds(sceneId));

  const pairs: PairPlan[] =
    scene.shots.length === 1
      ? [{ startShot: scene.shots[0], endShot: undefined }]
      : scene.shots.slice(0, -1).map((startShot, i) => ({ startShot, endShot: scene.shots[i + 1] }));

  const overrideIds = [...new Set(pairs.map((p) => p.startShot.videoModelId).filter((id): id is string => !!id))];
  const overrideOptions = overrideIds.length
    ? await prisma.aiModelOption.findMany({
        where: { id: { in: overrideIds }, jobType: "VIDEO_GENERATION", isEnabled: true },
      })
    : [];
  const overrideById = new Map(overrideOptions.map((o) => [o.id, o]));

  // Only fetched if at least one pair actually needs the rule lookup — most
  // scenes have no preferredCameraMovements configured at all.
  let cameraMovementOptions: Awaited<ReturnType<typeof listModelsForJob>> | null = null;
  async function resolveCameraMovementModel(movement: CameraMovement) {
    cameraMovementOptions ??= await listModelsForJob("VIDEO_GENERATION");
    return (
      cameraMovementOptions.find((o) => parseVideoModelConfig(o.config)?.preferredCameraMovements?.includes(movement)) ?? null
    );
  }

  async function resolvePairModel(shot: SceneShot): Promise<ResolvedPairModel> {
    const override = shot.videoModelId ? overrideById.get(shot.videoModelId) : undefined;
    if (override) return { modelId: override.modelId, modelConfig: parseVideoModelConfig(override.config) };
    const ruled = await resolveCameraMovementModel(shot.cameraMovement);
    if (ruled) return { modelId: ruled.modelId, modelConfig: parseVideoModelConfig(ruled.config) };
    return fallback;
  }

  const pairModels = await Promise.all(pairs.map((pair) => resolvePairModel(pair.startShot)));

  function sameFixedDurations(a: VideoModelConfig | null, b: VideoModelConfig | null): boolean {
    if (a?.durationMode !== "fixed" || b?.durationMode !== "fixed") return false;
    const av = [...(a.fixedDurations ?? [])].sort((x, y) => x - y);
    const bv = [...(b.fixedDurations ?? [])].sort((x, y) => x - y);
    return av.length === bv.length && av.every((v, i) => v === bv[i]);
  }
  // splitFixedDurations jointly optimizes every pair's duration against one
  // shared set of fixed-duration steps (e.g. 14s over 2 pairs on [4,6,8]s
  // options -> [8,6], not two independently-rounded 8s legs overshooting to
  // 16s). That optimization only means something when every routed pair
  // actually shares the same fixed-duration model — once routing sends pairs
  // to different models, fall back to a plain even split and let each pair's
  // own planVideoSegments call clamp independently to its own model.
  const sharedFixedConfig =
    pairModels[0]?.modelConfig?.durationMode === "fixed" &&
    pairModels.every((pm) => sameFixedDurations(pm.modelConfig, pairModels[0].modelConfig))
      ? pairModels[0].modelConfig
      : null;

  const autoPairTargets =
    sceneTargetDuration && sharedFixedConfig
      ? splitFixedDurations(sceneTargetDuration, pairs.length, sharedFixedConfig.fixedDurations ?? [])
      : pairs.map(() => (sceneTargetDuration ? sceneTargetDuration / pairs.length : undefined));

  return { pairs, pairModels, sceneTargetDuration, autoPairTargets };
}

interface GeneratedSegment {
  buffer: Buffer;
  mimeType: string;
  prompt: string;
  sourceImageId?: string;
  // null = not checked (see checkSegmentFrozen) — never treated as a hard
  // failure, only surfaced as an advisory flag on the stored Asset.
  qcPassed: boolean | null;
  qcNotes: string | null;
  usedEndFrame: boolean;
  // null = not checked — either no VIDEO_VALIDATION model configured, or the
  // check itself failed (advisory only, see runVideoValidation's caller).
  // Distinct from qcPassed above: this checks identity/reference/continuity/
  // prompt adherence via a vision-LLM critic, qcPassed checks freeze/
  // near-static via deterministic local ffmpeg analysis.
  validationPassed: boolean | null;
  validationNotes: string | null;
}

// A STATIC-camera shot is allowed to look still — that's the point — so only
// shots that actually requested camera movement get checked at all. Frozen
// for most of the clip despite requested movement means the model likely
// just returned the starting image with a codec wrapper around it, the most
// common image-to-video failure mode. Advisory-only: a tool failure here
// (ffmpeg missing, corrupt temp file, etc.) must never block a successful
// generation, so it's swallowed into "not checked" rather than thrown.
const FREEZE_FLAG_FRACTION = 0.6;

async function checkSegmentFrozen(
  filePath: string,
  cameraMovement: CameraMovement
): Promise<{ checked: boolean; flagged: boolean; note: string | null }> {
  // HANDHELD is deliberately NOT exempted alongside STATIC. The concern would
  // be that handheld's small amplitude reads as frozen, but detectFrozenSeconds
  // runs freezedetect at n=-60dB (see lib/ffmpeg.ts) — roughly 0.1% of full
  // scale, far below any real handheld drift. A HANDHELD clip that does trip
  // this threshold genuinely has no motion in it, which is exactly the failure
  // this check exists to catch, so exempting it would only hide a true positive.
  if (cameraMovement === "STATIC") return { checked: false, flagged: false, note: null };
  try {
    const [durationSeconds, frozenSeconds] = await Promise.all([probeDuration(filePath), detectFrozenSeconds(filePath)]);
    const flagged = frozenSeconds >= durationSeconds * FREEZE_FLAG_FRACTION;
    return {
      checked: true,
      flagged,
      note: flagged
        ? `Looked frozen for ~${frozenSeconds.toFixed(1)}s of ${durationSeconds.toFixed(1)}s despite requesting ${cameraMovement}.`
        : null,
    };
  } catch {
    return { checked: false, flagged: false, note: null };
  }
}

// Runs one pair's frame-chained generation loop (start image -> N sub-segment
// calls, seeded with the previous call's own last frame — see
// chainNextFrame), invoking `onSegment` for each generated buffer rather than
// persisting anything itself. generateSceneVideo's onSegment stores each
// segment immediately as it's generated (matches the pre-existing
// crash-safety behavior: a mid-batch failure still leaves earlier segments
// persisted); regenerateScenePairVideo's instead collects them so the
// existing take's clips for this pair are only replaced once every
// sub-segment of the retake has actually succeeded.
async function generatePairSegments(params: {
  projectId: string;
  pair: PairPlan;
  pairIndex: number;
  pairModel: ResolvedPairModel;
  pairTarget: number | undefined;
  pairPrompt: string;
  resolvedResolution: string | undefined;
  resolvedGenerateAudio: boolean | undefined;
  castReferenceDataUris: string[];
  workDir: string;
  // Tier-2 critic inputs — null validationModelId means "no model
  // configured," which short-circuits the check entirely (zero cost by
  // default, same posture as IMAGE_VALIDATION and checkSegmentFrozen).
  validationModelId: string | null;
  validationEntities: ValidationEntity[];
  validationReferenceDataUris: string[];
  onSegment: (segment: GeneratedSegment) => Promise<void>;
}): Promise<void> {
  const {
    projectId,
    pair,
    pairIndex,
    pairModel,
    pairTarget,
    pairPrompt,
    resolvedResolution,
    resolvedGenerateAudio,
    castReferenceDataUris,
    workDir,
    validationModelId,
    validationEntities,
    validationReferenceDataUris,
    onSegment,
  } = params;

  const startDataUri = await loadShotImageDataUri(pair.startShot);
  const supportsLastFrame = pairModel.modelConfig?.supportsLastFrame !== false;
  const endDataUri = pair.endShot && supportsLastFrame ? await loadShotImageDataUri(pair.endShot) : undefined;

  const subSegmentDurations = pairTarget ? planVideoSegments(pairTarget, pairModel.modelConfig).durations : [undefined];

  async function generateOnce(subDuration: number | undefined, isLastSub: boolean, segmentPrompt: string, imageDataUri: string) {
    const startedAt = Date.now();
    let generated: { base64: string; mimeType: string; costUsd?: number };
    try {
      generated = await generateVideo({
        modelId: pairModel.modelId,
        prompt: segmentPrompt,
        imageDataUri,
        lastFrameDataUri: isLastSub ? endDataUri : undefined,
        durationSeconds: subDuration,
        generateAudio: resolvedGenerateAudio,
        resolution: resolvedResolution,
        inputReferenceDataUris: castReferenceDataUris,
      });
    } catch (error) {
      await recordGenerationEvent({
        jobType: "VIDEO_GENERATION",
        provider: "openrouter",
        modelId: pairModel.modelId,
        projectId,
        entityType: "SHOT",
        entityId: pair.startShot.id,
        durationMs: Date.now() - startedAt,
        success: false,
        errorMessage: error instanceof Error ? error.message : String(error),
      });
      throw error;
    }
    await recordGenerationEvent({
      jobType: "VIDEO_GENERATION",
      provider: "openrouter",
      modelId: pairModel.modelId,
      projectId,
      entityType: "SHOT",
      entityId: pair.startShot.id,
      costUsd: generated.costUsd,
      durationMs: Date.now() - startedAt,
      success: true,
    });
    return { buffer: Buffer.from(generated.base64, "base64"), mimeType: generated.mimeType };
  }

  let chainedFrame = startDataUri;
  for (const [subIndex, subDuration] of subSegmentDurations.entries()) {
    const isLastSub = subIndex === subSegmentDurations.length - 1;
    const segmentPrompt = subSegmentPrompt(pairPrompt, subIndex, subSegmentDurations.length);

    let { buffer, mimeType } = await generateOnce(subDuration, isLastSub, segmentPrompt, chainedFrame);
    const qcPath = path.join(workDir, `qc-pair${pairIndex}-seg${subIndex}-a1.${extFromMime(mimeType)}`);
    await fs.writeFile(qcPath, buffer);
    let qc = await checkSegmentFrozen(qcPath, pair.startShot.cameraMovement);

    if (qc.checked && qc.flagged) {
      // One automatic retry on a flagged result — same model/prompt/input,
      // just rolling the dice again. Whatever the retry produces is kept
      // either way (even if it's flagged too), matching validationPassed's
      // existing "advisory only, never blocking" contract elsewhere on
      // Asset: the flag is a signal for the user to notice and manually
      // retake if they want, not a hard gate on generation completing.
      const retry = await generateOnce(subDuration, isLastSub, segmentPrompt, chainedFrame);
      buffer = retry.buffer;
      mimeType = retry.mimeType;
      const retryQcPath = path.join(workDir, `qc-pair${pairIndex}-seg${subIndex}-a2.${extFromMime(mimeType)}`);
      await fs.writeFile(retryQcPath, buffer);
      qc = await checkSegmentFrozen(retryQcPath, pair.startShot.cameraMovement);
    }

    let validation: { passed: boolean; notes: string } | null = null;
    if (validationModelId) {
      try {
        const generatedDataUri = `data:${mimeType};base64,${buffer.toString("base64")}`;
        validation = await runVideoValidation(
          generatedDataUri,
          validationEntities,
          validationReferenceDataUris,
          validationModelId,
          parseContinuitySnapshot(pair.startShot.continuity),
          pair.startShot.continuityNotes,
          pairPrompt
        );
      } catch {
        // Advisory only — an unreachable/misconfigured validation model must
        // never block a successful generation from being stored.
        validation = null;
      }
    }

    await onSegment({
      buffer,
      mimeType,
      prompt: segmentPrompt,
      sourceImageId: subIndex === 0 ? pair.startShot.images[0]?.id : undefined,
      qcPassed: qc.checked ? !qc.flagged : null,
      qcNotes: qc.note,
      usedEndFrame: isLastSub && endDataUri !== undefined,
      validationPassed: validation?.passed ?? null,
      validationNotes: validation?.notes ?? null,
    });

    if (!isLastSub) {
      chainedFrame = await chainNextFrame(workDir, buffer, mimeType, `pair${pairIndex}-seg${subIndex}`);
    }
  }
}

interface GenerateSceneVideoParams {
  sceneId: string;
  modelId: string;
  // The chosen model's admin-configured capabilities (AiModelOption.config),
  // resolved by the caller so this function doesn't need its own lookup.
  // null means "unconfigured" — falls back to one unconstrained-duration
  // segment, matching the pre-multi-segment behavior.
  modelConfig: VideoModelConfig | null;
  resolution?: string;
  generateAudio?: boolean;
  // Opt-in only — never set by the generic scene video panel, so every other
  // model's behavior is unchanged. When true, resolves this scene's locked
  // characters' + tagged locations' reference images (same roster
  // generateShotImage() already uses for image-generation consistency, see
  // lib/shot-images.ts) and sends them as OpenRouter's `input_references` —
  // identity/style guidance distinct from the per-pair keyframes below. Added
  // for the Seedance 2.5 Studio page, whose prompting model treats "give
  // every reference a single job" as a first-class practice.
  includeCastReferences?: boolean;
  // null/undefined = no VIDEO_VALIDATION model configured — skips the check
  // entirely, same zero-cost-by-default posture as IMAGE_VALIDATION.
  validationModelId?: string | null;
}

// IMAGE_TO_VIDEO scenes generate one clip per consecutive shot pair
// (shot[i]->shot[i+1]), so every shot's image is an actual keyframe instead
// of just the first and last mattering. A 1-shot scene is a single
// degenerate "pair" with no end keyframe (plain image animation, as before).
// TEXT_TO_VIDEO scenes don't use shots at all and keep their own flat,
// duration-segmented loop. Either way, segments within one leg (a pair, or
// the whole TEXT_TO_VIDEO clip) beyond what the model can produce in one
// call are frame-chained: each one after the first is seeded with the
// previous call's own last frame (extracted via ffmpeg). All clips from one
// "Generate Video" click share a videoBatchId and a single ascending
// videoSegmentOrder across every pair, so assembly (which just concatenates
// a scene's selected clips in videoSegmentOrder) needs no awareness of
// pairs at all. Generation is necessarily sequential, not parallel, since
// each call can depend on the previous one's output.
export async function generateSceneVideo({
  sceneId,
  modelId,
  modelConfig,
  resolution,
  generateAudio,
  includeCastReferences,
  validationModelId,
}: GenerateSceneVideoParams): Promise<SerializedSceneVideoClip[]> {
  const scene = await loadSceneForVideoGeneration(sceneId);

  if (scene.visualMode !== "IMAGE_TO_VIDEO" && scene.visualMode !== "TEXT_TO_VIDEO") {
    throw new OpenRouterError("This scene's Visual Mode isn't Image → Video or Text → Video.");
  }

  const resolvedResolution = resolution ?? scene.videoResolution ?? modelConfig?.resolutions?.[0] ?? undefined;
  const resolvedGenerateAudio = generateAudio ?? scene.videoGenerateAudio;
  const castReferenceDataUris = await resolveCastReferenceDataUris(scene, includeCastReferences);
  const projectId = await resolveSceneProjectId(sceneId);
  const resolvedValidationModelId = validationModelId ?? null;
  const validationEntities = resolveValidationTargets(scene);
  const validationReferenceDataUris =
    validationEntities.length > 0 ? await loadReferenceDataUris(validationEntities) : [];

  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "narrata-video-segment-"));
  try {
    // Deselect the scene's previous take up front, not after — the calls
    // below are sequential external requests that can take minutes and can
    // fail partway through, and leaving the old batch selected while a new
    // one is in progress is a safer failure mode than briefly having two
    // different "selected" batches at once.
    await prisma.asset.updateMany({ where: { videoSceneId: sceneId, isSelected: true }, data: { isSelected: false } });

    const batchId = randomUUID();
    const created: Asset[] = [];
    let globalOrder = 0;

    async function storeClip(
      buffer: Buffer,
      mimeType: string,
      // modelId is per-call, not the outer scene-level default — IMAGE_TO_VIDEO
      // pairs can each resolve to a different model (see resolvePairModel in
      // buildImageToVideoPlan), and the stored Asset.modelId should reflect
      // which one actually generated that segment.
      fields: {
        prompt: string;
        modelId: string;
        sourceImageId?: string;
        videoPairIndex?: number;
        qcPassed?: boolean | null;
        qcNotes?: string | null;
        usedEndFrame?: boolean | null;
        validationPassed?: boolean | null;
        validationNotes?: string | null;
      }
    ): Promise<void> {
      const ext = extFromMime(mimeType);
      const order = globalOrder++;
      const fileName = `scene-video-segment${order}.${ext}`;
      const key = buildStorageKey("scenes", sceneId, `${batchId}-${fileName}`);
      await storage.put(key, buffer);
      const asset = await prisma.asset.create({
        data: {
          type: "VIDEO_CLIP",
          storageKey: key,
          fileName,
          mimeType,
          sizeBytes: buffer.byteLength,
          videoSceneId: sceneId,
          isSelected: true,
          createdBy: "AI",
          videoBatchId: batchId,
          videoSegmentOrder: order,
          ...fields,
          // Only recorded when a check actually ran (fields.validationPassed
          // set to a boolean) — mirrors shot-images.ts's identical ternary,
          // so a null/never-checked segment never carries a stale model id.
          validationModelId: fields.validationPassed != null ? resolvedValidationModelId : null,
        },
      });
      created.push(asset);
    }

    if (scene.visualMode === "IMAGE_TO_VIDEO") {
      if (scene.shots.length === 0) {
        throw new OpenRouterError("Add at least one shot with a selected image before generating a video clip.");
      }
      scene.shots.forEach((shot, i) => {
        if (!shot.images[0]) {
          throw new OpenRouterError(`Shot ${i + 1} needs a selected image before generating a video clip.`);
        }
      });

      const { pairs, pairModels, autoPairTargets } = await buildImageToVideoPlan(scene, sceneId, { modelId, modelConfig });

      for (const [pairIndex, pair] of pairs.entries()) {
        const pairModel = pairModels[pairIndex];
        const pairTarget = pair.startShot.durationSeconds ?? autoPairTargets[pairIndex];
        const pairPrompt = buildPairPrompt(scene, pair, pairs[pairIndex - 1]);

        await generatePairSegments({
          projectId,
          pair,
          pairIndex,
          pairModel,
          pairTarget,
          pairPrompt,
          resolvedResolution,
          resolvedGenerateAudio,
          castReferenceDataUris,
          workDir,
          validationModelId: resolvedValidationModelId,
          validationEntities,
          validationReferenceDataUris,
          onSegment: (seg) =>
            storeClip(seg.buffer, seg.mimeType, {
              prompt: seg.prompt,
              modelId: pairModel.modelId,
              sourceImageId: seg.sourceImageId,
              videoPairIndex: pairIndex,
              qcPassed: seg.qcPassed,
              qcNotes: seg.qcNotes,
              usedEndFrame: seg.usedEndFrame,
              validationPassed: seg.validationPassed,
              validationNotes: seg.validationNotes,
            }),
        });
      }
    } else {
      const prompt = scene.videoPrompt?.trim() || scene.description;
      const targetDuration = scene.videoDurationSeconds ?? (await getSceneVoiceDurationSeconds(sceneId));
      const segmentDurations = targetDuration ? planVideoSegments(targetDuration, modelConfig).durations : [undefined];

      let chainedFrame: string | undefined;
      for (const [index, segmentDuration] of segmentDurations.entries()) {
        const segmentPrompt = subSegmentPrompt(prompt, index, segmentDurations.length);
        const videoStartedAt = Date.now();
        let generated: { base64: string; mimeType: string; costUsd?: number };
        try {
          generated = await generateVideo({
            modelId,
            prompt: segmentPrompt,
            imageDataUri: chainedFrame,
            durationSeconds: segmentDuration,
            generateAudio: resolvedGenerateAudio,
            resolution: resolvedResolution,
            inputReferenceDataUris: castReferenceDataUris,
          });
        } catch (error) {
          await recordGenerationEvent({
            jobType: "VIDEO_GENERATION",
            provider: "openrouter",
            modelId,
            projectId,
            entityType: "SCENE",
            entityId: sceneId,
            durationMs: Date.now() - videoStartedAt,
            success: false,
            errorMessage: error instanceof Error ? error.message : String(error),
          });
          throw error;
        }
        await recordGenerationEvent({
          jobType: "VIDEO_GENERATION",
          provider: "openrouter",
          modelId,
          projectId,
          entityType: "SCENE",
          entityId: sceneId,
          costUsd: generated.costUsd,
          durationMs: Date.now() - videoStartedAt,
          success: true,
        });

        const buffer = Buffer.from(generated.base64, "base64");

        // TEXT_TO_VIDEO has no Shot/continuity to check — reference
        // consistency and prompt/motion adherence are still meaningful, so
        // the check still runs, just with empty continuity facts.
        let validation: { passed: boolean; notes: string } | null = null;
        if (resolvedValidationModelId) {
          try {
            const generatedDataUri = `data:${generated.mimeType};base64,${buffer.toString("base64")}`;
            validation = await runVideoValidation(
              generatedDataUri,
              validationEntities,
              validationReferenceDataUris,
              resolvedValidationModelId,
              [],
              null,
              prompt
            );
          } catch {
            validation = null;
          }
        }

        await storeClip(buffer, generated.mimeType, {
          prompt: segmentPrompt,
          modelId,
          validationPassed: validation?.passed ?? null,
          validationNotes: validation?.notes ?? null,
        });

        if (index < segmentDurations.length - 1) {
          chainedFrame = await chainNextFrame(workDir, buffer, generated.mimeType, `segment${index}`);
        }
      }
    }

    return created.map(serializeSceneVideoClip);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true });
  }
}

interface RegenerateScenePairVideoParams {
  sceneId: string;
  pairIndex: number;
  modelId: string;
  modelConfig: VideoModelConfig | null;
  resolution?: string;
  generateAudio?: boolean;
  includeCastReferences?: boolean;
  validationModelId?: string | null;
}

// Retakes a single shot pair within the scene's currently *selected* take,
// instead of regenerating the whole scene. Pairs are independent generation
// units — each starts from its own shot's fixed image, not chained from the
// previous pair's output — so a bad 6s pair inside a 45s scene doesn't need
// the other 39s regenerated (and re-paid-for) just to fix it. Replaces that
// pair's segment(s) in place within the same batchId and renumbers the
// batch's segment order (the retake's own sub-segment count can differ from
// what it's replacing), rather than creating a whole new take — the Takes
// panel's "Use this take"/delete-take actions stay whole-batch, unaffected.
export async function regenerateScenePairVideo({
  sceneId,
  pairIndex,
  modelId,
  modelConfig,
  resolution,
  generateAudio,
  includeCastReferences,
  validationModelId,
}: RegenerateScenePairVideoParams): Promise<SerializedSceneVideoClip[]> {
  const scene = await loadSceneForVideoGeneration(sceneId);

  if (scene.visualMode !== "IMAGE_TO_VIDEO") {
    throw new OpenRouterError("Retaking a single shot pair only applies to Image → Video scenes.");
  }
  if (scene.shots.length === 0 || !scene.shots.every((shot) => shot.images[0])) {
    throw new OpenRouterError("Every shot needs a selected image before retaking a video clip.");
  }

  const selectedClips = await prisma.asset.findMany({
    where: { videoSceneId: sceneId, isSelected: true },
    orderBy: { videoSegmentOrder: "asc" },
  });
  const batchId = selectedClips[0]?.videoBatchId;
  if (!batchId || selectedClips.some((c) => c.videoBatchId !== batchId)) {
    throw new OpenRouterError("Generate a full video take before retaking a single shot pair.");
  }
  const oldPairAssets = selectedClips.filter((c) => c.videoPairIndex === pairIndex);
  if (oldPairAssets.length === 0) {
    throw new OpenRouterError("The selected take has no clip for that shot pair.");
  }

  const resolvedResolution = resolution ?? scene.videoResolution ?? modelConfig?.resolutions?.[0] ?? undefined;
  const resolvedGenerateAudio = generateAudio ?? scene.videoGenerateAudio;
  const castReferenceDataUris = await resolveCastReferenceDataUris(scene, includeCastReferences);
  const projectId = await resolveSceneProjectId(sceneId);
  const resolvedValidationModelId = validationModelId ?? null;
  const validationEntities = resolveValidationTargets(scene);
  const validationReferenceDataUris =
    validationEntities.length > 0 ? await loadReferenceDataUris(validationEntities) : [];

  const { pairs, pairModels, autoPairTargets } = await buildImageToVideoPlan(scene, sceneId, { modelId, modelConfig });
  const pair = pairs[pairIndex];
  if (!pair) {
    throw new OpenRouterError("That shot pair no longer exists — the scene's shots may have changed.");
  }
  const pairModel = pairModels[pairIndex];
  const pairTarget = pair.startShot.durationSeconds ?? autoPairTargets[pairIndex];
  const pairPrompt = buildPairPrompt(scene, pair, pairs[pairIndex - 1]);

  const workDir = await fs.mkdtemp(path.join(os.tmpdir(), "narrata-video-retake-"));
  try {
    // Collected, not persisted, as they're generated — the existing take's
    // clips for this pair are only touched once every sub-segment of the
    // retake has actually succeeded, so a mid-generation failure leaves the
    // take exactly as it was.
    const newSegments: GeneratedSegment[] = [];
    await generatePairSegments({
      projectId,
      pair,
      pairIndex,
      pairModel,
      pairTarget,
      pairPrompt,
      resolvedResolution,
      resolvedGenerateAudio,
      castReferenceDataUris,
      workDir,
      validationModelId: resolvedValidationModelId,
      validationEntities,
      validationReferenceDataUris,
      onSegment: async (seg) => {
        newSegments.push(seg);
      },
    });

    for (const old of oldPairAssets) {
      await storage.remove(old.storageKey);
    }
    await prisma.asset.deleteMany({ where: { id: { in: oldPairAssets.map((a) => a.id) } } });

    for (const [i, seg] of newSegments.entries()) {
      const ext = extFromMime(seg.mimeType);
      const key = buildStorageKey("scenes", sceneId, `${batchId}-retake-pair${pairIndex}-${randomUUID()}.${ext}`);
      await storage.put(key, seg.buffer);
      await prisma.asset.create({
        data: {
          type: "VIDEO_CLIP",
          storageKey: key,
          fileName: `scene-video-segment.${ext}`,
          mimeType: seg.mimeType,
          sizeBytes: seg.buffer.byteLength,
          videoSceneId: sceneId,
          isSelected: true,
          createdBy: "AI",
          videoBatchId: batchId,
          // Temporary — the whole batch is renumbered by (pairIndex, this
          // relative order) right below, since the retake's own sub-segment
          // count may differ from what it's replacing.
          videoSegmentOrder: 1_000_000 + i,
          videoPairIndex: pairIndex,
          modelId: pairModel.modelId,
          prompt: seg.prompt,
          sourceImageId: seg.sourceImageId,
          qcPassed: seg.qcPassed,
          qcNotes: seg.qcNotes,
          usedEndFrame: seg.usedEndFrame,
          validationPassed: seg.validationPassed,
          validationNotes: seg.validationNotes,
          validationModelId: seg.validationPassed != null ? resolvedValidationModelId : null,
        },
      });
    }

    const batchAssets = await prisma.asset.findMany({ where: { videoSceneId: sceneId, videoBatchId: batchId } });
    batchAssets.sort(
      (a, b) => (a.videoPairIndex ?? 0) - (b.videoPairIndex ?? 0) || (a.videoSegmentOrder ?? 0) - (b.videoSegmentOrder ?? 0)
    );
    for (const [order, asset] of batchAssets.entries()) {
      if (asset.videoSegmentOrder !== order) {
        await prisma.asset.update({ where: { id: asset.id }, data: { videoSegmentOrder: order } });
      }
    }

    const finalBatch = await prisma.asset.findMany({
      where: { videoSceneId: sceneId, videoBatchId: batchId },
      orderBy: { videoSegmentOrder: "asc" },
    });
    return finalBatch.map(serializeSceneVideoClip);
  } finally {
    await fs.rm(workDir, { recursive: true, force: true });
  }
}

const MOTION_PROMPT_SYSTEM_PROMPT = `You are the Motion Prompt drafting step inside Narrata, a manual-first AI story/video production studio.
Write a camera/motion direction for an image-to-video model, continuing smoothly from the previous scene and animating the attached current-scene image. Describe only camera movement, subject motion, and action beats — not dialogue or narration, those are separate tracks handled elsewhere.

Direct the scene, don't describe an image — write in Subject → Action → Camera → Style order, matching this JSON shape:
- subject: who/what is in frame (kept short — the image already shows this, so only note what matters for the motion, e.g. "the sealed stone door").
- action: what happens/moves during the clip, in playback order.
- camera: one explicit camera move (e.g. "slow dolly-in from a low angle"). Never leave this blank — an unstated camera reads as aimless drift.
- style: lighting/mood/lens notes, or "" if the image's existing style needs no extra direction.

When a "# Shot direction already resolved for this scene" section is present in the user prompt, the camera and lighting for these shots have ALREADY been decided by the Director. Your camera and style fields must express that existing direction — phrase its angle, lens and framing progression as a single concrete camera move, and its lighting as the style note. Never substitute a different move, angle or lighting look, and never contradict it. Only when that section is absent (or says nothing about an axis) do you invent that part yourself, exactly as described above.
- beatHook, beatDevelopment, beatEscalation, beatResolution: timed beats for longer clips (roughly 0-5s / 5-16s / 16-25s / 25-30s). Leave all four as "" for a short, single-beat clip — only fill them in when the action genuinely needs staged timing.
- ending: how the clip resolves (a held frame, a pull-back, a specific gesture). Never leave this blank — always direct how it ends.`;

interface DraftMotionPromptParams {
  sceneId: string;
  modelId: string;
}

// Without this, two AI steps independently invent camera intent for the same
// scene: SHOT_PLANNING resolves per-shot cinematography, and this drafting
// call — which never saw it — writes its own competing camera/style from the
// image alone. Summarizing the resolved direction here turns the second call
// into an expression of the first rather than a rival to it.
//
// Returns null when no shot in the scene has any resolved direction (legacy
// scenes, hand-added shots), which restores today's invent-one-from-scratch
// behavior via the system prompt's "only when that section is absent" clause.
function buildResolvedDirectionBlock(shots: ShotCinematography[]): string | null {
  const directed = shots.filter(hasCameraDirection);
  if (directed.length === 0) return null;

  const lines = shots.map((shot, index) => {
    const parts = [
      shot.shotSize && SHOT_SIZE_LABELS[shot.shotSize],
      shot.cameraAngle && CAMERA_ANGLE_LABELS[shot.cameraAngle],
      shot.lensMm !== null && `${shot.lensMm}mm lens`,
      shot.depthOfField && DEPTH_OF_FIELD_LABELS[shot.depthOfField],
      shot.lightingStyle && LIGHTING_STYLE_LABELS[shot.lightingStyle],
      shot.focusPoint && `focus on ${shot.focusPoint}`,
      shot.subjectMovement && `subject movement: ${shot.subjectMovement}`,
    ].filter(Boolean);
    return `Shot ${index + 1}: ${parts.length > 0 ? parts.join("; ") : "(no direction resolved)"}`;
  });

  return `# Shot direction already resolved for this scene\nThese were decided by the Director for this scene's shots. Express them in your camera and style fields — do not invent a different camera move or lighting look.\n${lines.join("\n")}`;
}

const motionPromptDraftSchema = z.object({
  subject: z.string(),
  action: z.string(),
  camera: z.string(),
  style: z.string(),
  beatHook: z.string(),
  beatDevelopment: z.string(),
  beatEscalation: z.string(),
  beatResolution: z.string(),
  ending: z.string(),
});

const MOTION_PROMPT_JSON_SCHEMA = {
  type: "object",
  properties: {
    subject: { type: "string" },
    action: { type: "string" },
    camera: { type: "string" },
    style: { type: "string" },
    beatHook: { type: "string" },
    beatDevelopment: { type: "string" },
    beatEscalation: { type: "string" },
    beatResolution: { type: "string" },
    ending: { type: "string" },
  },
  required: ["subject", "action", "camera", "style", "beatHook", "beatDevelopment", "beatEscalation", "beatResolution", "ending"],
  additionalProperties: false,
} as const;

// Reads the previous scene's generated clip (visually and, via OpenRouter's
// video-input content part, its audio too) plus the current scene's selected
// starting frame, in one multimodal call — grounding the drafted motion
// prompt in what actually happened last, not just what was planned. Falls
// back to the previous scene's description text when it has no selected clip
// yet (first scene, or video not generated yet). Returns a draft only — the
// caller/UI decides whether to accept it into the editable motionPrompt
// field, same "AI drafts, user approves" pattern as every other drafting job.
export async function draftMotionPrompt({ sceneId, modelId }: DraftMotionPromptParams): Promise<PromptBuilderFields> {
  // Every shot, not just the first: shots[0] still supplies the starting
  // frame, but the whole ordered list is needed to summarize the Director's
  // resolved cinematography for this scene (see buildResolvedDirectionBlock).
  const scene = await prisma.scene.findUniqueOrThrow({
    where: { id: sceneId },
    include: {
      shots: { orderBy: { order: "asc" }, include: { images: { where: { isSelected: true }, take: 1 } } },
    },
  });

  if (scene.visualMode !== "IMAGE_TO_VIDEO") {
    throw new OpenRouterError("Motion prompt drafting only applies to Image → Video scenes.");
  }

  const currentImage = scene.shots[0]?.images[0];
  if (!currentImage) {
    throw new OpenRouterError("Generate and select a first-shot image before drafting a motion prompt.");
  }
  const currentImageBytes = await storage.get(currentImage.storageKey);
  if (!currentImageBytes) {
    throw new OpenRouterError("The first shot's selected image is missing from storage.");
  }
  const currentImageDataUri = `data:${currentImage.mimeType ?? "image/png"};base64,${currentImageBytes.toString("base64")}`;

  const parentWhere = scene.storyId ? { storyId: scene.storyId } : { episodeId: scene.episodeId! };
  const previousScene = await prisma.scene.findFirst({
    where: { ...parentWhere, order: scene.order - 1 },
    // The *last* segment of the previous scene's selected batch — that's
    // the frame this scene actually continues from when the previous scene
    // was multi-segment, not its first.
    include: { videoClips: { where: { isSelected: true }, orderBy: { videoSegmentOrder: "desc" }, take: 1 } },
  });

  let previousVideoDataUri: string | undefined;
  const previousClip = previousScene?.videoClips[0];
  if (previousClip) {
    const clipBytes = await storage.get(previousClip.storageKey);
    if (clipBytes) {
      previousVideoDataUri = `data:${previousClip.mimeType ?? "video/mp4"};base64,${clipBytes.toString("base64")}`;
    }
  }

  const previousContext = !previousScene
    ? "This is the first scene — there is no preceding scene."
    : previousVideoDataUri
      ? "The attached video is the immediately preceding scene's generated clip — watch and listen to it (dialogue, sound, motion, camera, ending framing) before writing the motion prompt below, so this scene continues naturally from it."
      : `The immediately preceding scene has no generated clip yet. Its description: "${previousScene.description}"`;

  const resolvedDirection = buildResolvedDirectionBlock(scene.shots);

  const userPrompt = [
    `# Previous scene\n${previousContext}`,
    `# Current scene\nDescription: ${scene.description}\nThe attached image is this scene's starting frame — motion should build on what's actually in it, not a generic description.`,
    resolvedDirection,
    "Write the motion prompt now.",
  ]
    .filter(Boolean)
    .join("\n\n");

  const raw = await callChatModel({
    modelId,
    systemPrompt: MOTION_PROMPT_SYSTEM_PROMPT,
    userPrompt,
    images: [currentImageDataUri],
    videos: previousVideoDataUri ? [previousVideoDataUri] : undefined,
    jsonSchema: { name: "motion_prompt_draft", schema: MOTION_PROMPT_JSON_SCHEMA },
    temperature: 0.7,
  });

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(raw);
  } catch {
    throw new OpenRouterError("AI returned invalid JSON.");
  }

  const parsed = motionPromptDraftSchema.safeParse(parsedJson);
  if (!parsed.success) {
    throw new OpenRouterError("AI returned an unexpected shape.");
  }

  return parsed.data;
}

const DURATION_RECOMMENDATION_SYSTEM_PROMPT = `You are the Duration Recommendation step inside Narrata, a manual-first AI story/video production studio.
Read the scene below and recommend how many seconds its generated video clip should run.

Judge pacing like an editor: a quick action beat or a single line of dialogue runs shorter; a slow establishing shot, a wide emotional beat, or a scene carrying more spoken content runs longer. If a "Spoken audio" length is given, treat it as a floor the clip must cover, not a ceiling — pad for visual breathing room (a beat before/after the line) rather than cutting it flush.

Respond with strict JSON only — no prose, no markdown code fences, no commentary. The JSON must match this shape exactly:
{
  "durationSeconds": a whole number of seconds, typically between 2 and 30,
  "reason": "one short sentence explaining the pacing call"
}`;

const durationRecommendationSchema = z.object({
  durationSeconds: z.number().positive(),
  reason: z.string().min(1),
});

export interface DurationRecommendation {
  durationSeconds: number;
  reason: string;
}

interface RecommendVideoDurationParams {
  sceneId: string;
  modelId: string;
}

// Text-only reasoning call (no image/video input, unlike draftMotionPrompt
// above) — feeds the recommended seconds into the same editable `duration`
// field the panel already has, same "AI proposes, user reviews and saves"
// idiom as the rest of this file. voiceDurationSeconds (from
// getSceneVoiceDurationSeconds, already used as the *generation-time*
// fallback when duration is left blank) is passed here too, as a floor hint
// rather than the answer itself — a scene can run longer than its dialogue
// for visual pacing, just never shorter.
export async function recommendVideoDuration({ sceneId, modelId }: RecommendVideoDurationParams): Promise<DurationRecommendation> {
  const scene = await prisma.scene.findUniqueOrThrow({ where: { id: sceneId } });

  const voiceDurationSeconds = await getSceneVoiceDurationSeconds(sceneId);
  const motionOrVideoPrompt =
    scene.visualMode === "TEXT_TO_VIDEO" ? scene.videoPrompt : scene.motionPrompt;

  const promptLines = [
    `Description: ${scene.description}`,
    motionOrVideoPrompt?.trim() ? `Motion/video prompt: ${motionOrVideoPrompt.trim()}` : null,
    scene.narration?.trim() ? `Narration: ${scene.narration.trim()}` : null,
    voiceDurationSeconds ? `Spoken audio: ${Math.round(voiceDurationSeconds * 10) / 10}s of recorded narration/dialogue already exists for this scene.` : null,
  ].filter((line): line is string => line !== null);

  const raw = await callChatModel({
    modelId,
    systemPrompt: DURATION_RECOMMENDATION_SYSTEM_PROMPT,
    userPrompt: `# Scene\n${promptLines.join("\n")}\n\nRecommend the duration now.`,
    jsonMode: true,
    temperature: 0.4,
  });

  let parsedJson: unknown;
  try {
    parsedJson = JSON.parse(raw);
  } catch {
    throw new OpenRouterError("AI returned invalid JSON.");
  }

  const parsed = durationRecommendationSchema.safeParse(parsedJson);
  if (!parsed.success) {
    throw new OpenRouterError("AI returned an unexpected shape.");
  }

  // The floor above is a prompt instruction, not a guarantee — models do
  // ignore it (seen in practice: 14s suggested against 33s of already-
  // recorded narration). Enforce it in code too, same as the
  // generation-time fallback already treats voice length as authoritative
  // (see getSceneVoiceDurationSeconds's callers). Rounds the floor up so the
  // clip fully covers the audio rather than landing a fraction short of it.
  const floor = voiceDurationSeconds ? Math.ceil(voiceDurationSeconds) : 0;
  const durationSeconds = Math.max(Math.round(parsed.data.durationSeconds), floor);
  const reason =
    durationSeconds > Math.round(parsed.data.durationSeconds)
      ? `${parsed.data.reason} (raised from the AI's ${Math.round(parsed.data.durationSeconds)}s to cover the ${floor}s of existing narration/dialogue audio.)`
      : parsed.data.reason;

  return { durationSeconds, reason };
}

export async function getSceneVideoClips(sceneId: string): Promise<SerializedSceneVideoClip[]> {
  const assets = await prisma.asset.findMany({
    where: { videoSceneId: sceneId },
    orderBy: [{ createdAt: "desc" }, { videoSegmentOrder: "asc" }],
  });
  return assets.map(serializeSceneVideoClip);
}

// Selecting a clip selects its whole batch (every segment generated by the
// same call) — a batch is one "take"; partial selection can't be assembled
// into a coherent clip. Legacy rows with no batchId (single-clip, pre
// multi-segment) fall back to selecting just that one asset.
export async function selectSceneVideoClip(sceneId: string, assetId: string): Promise<SerializedSceneVideoClip[]> {
  return prisma.$transaction(async (tx) => {
    const asset = await tx.asset.findUniqueOrThrow({ where: { id: assetId } });
    if (asset.videoSceneId !== sceneId) {
      throw new Error("Video clip does not belong to this scene.");
    }
    await tx.asset.updateMany({ where: { videoSceneId: sceneId, isSelected: true }, data: { isSelected: false } });
    const where = asset.videoBatchId ? { videoSceneId: sceneId, videoBatchId: asset.videoBatchId } : { id: assetId };
    await tx.asset.updateMany({ where, data: { isSelected: true, reviewedAt: new Date() } });
    const batch = await tx.asset.findMany({ where, orderBy: { videoSegmentOrder: "asc" } });
    return batch.map(serializeSceneVideoClip);
  });
}

// Deletes the whole batch a clip belongs to — a partial take (missing one of
// its segments) can't be assembled, so there's no useful state to leave
// behind by deleting just one segment. Legacy rows with no batchId delete
// just that one asset, same as before.
export async function deleteSceneVideoClip(sceneId: string, assetId: string): Promise<void> {
  const asset = await prisma.asset.findUniqueOrThrow({ where: { id: assetId } });
  if (asset.videoSceneId !== sceneId) {
    throw new Error("Video clip does not belong to this scene.");
  }
  const batch = asset.videoBatchId
    ? await prisma.asset.findMany({ where: { videoSceneId: sceneId, videoBatchId: asset.videoBatchId } })
    : [asset];
  for (const clip of batch) {
    await storage.remove(clip.storageKey);
  }
  await prisma.asset.deleteMany({ where: { id: { in: batch.map((c) => c.id) } } });
}

// Mirrors mapSceneVoiceData in lib/voice.ts — for the scene pages' initial
// SSR load, serializing the videoClips relation the same way the API routes
// below do, so the client gets an identical shape regardless of source.
export function mapSceneVideoData<T extends { videoClips: Asset[]; videoGenerationStartedAt: Date | null }>(scene: T) {
  return {
    ...scene,
    videoClips: scene.videoClips.map(serializeSceneVideoClip),
    videoGenerationStartedAt: scene.videoGenerationStartedAt?.toISOString() ?? null,
  };
}
